name = "mediumish"
license = "MIT"
licenselink = "https://github.com/lgaida/mediumish-theme-gohugo/blob/master/LICENSE"
description = "An elegant, mediumish theme for gohugo"
homepage = "http://lgaida.de"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Lenard Gaida"
  homepage = "lgaida.de"

# If porting an existing theme
[original]
  name = "wowthemesnet"
  homepage = "https://www.wowthemes.net/"
  repo = "https://github.com/wowthemesnet/mediumish-theme-jekyll"
